import React, { useState } from 'react';
import { PageHeader } from '../components/layout/PageHeader';
import { MetricCard } from '../components/common/MetricCard';
import { Card, CardHeader, CardTitle, CardBody } from '../components/common/Card';
import { Button } from '../components/common/Button';
import { TimelineItem } from '../components/common/TimelineItem';
import { usePlan } from '../context/PlanContext';
import { TaskModal } from '../components/shared/TaskModal';
import { ChevronLeft, ChevronRight, Calendar, Plus, CalendarCheck } from 'lucide-react';
import { useOutletContext } from 'react-router-dom';

export const TodayPage: React.FC = () => {
  const { schedule, planHealth, completeTask, startTask, pauseTask, removeTask, refreshPlan } = usePlan();
  const { openUrgentModal } = useOutletContext<{ openUrgentModal: () => void }>();
  const [isTaskModalOpen, setIsTaskModalOpen] = useState(false);

  const todayDateStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const plannedMins = schedule.reduce((sum, s) => sum + s.durationMinutes, 0);
  const plannedHoursFormatted = `${Math.floor(plannedMins / 60)}h ${plannedMins % 60}m`;
  const availableHoursFormatted = `${Math.floor(planHealth.totalAvailableHours)}h ${Math.round((planHealth.totalAvailableHours % 1) * 60)}m`;
  const bufferHoursFormatted = `${Math.floor(planHealth.bufferHours)}h ${Math.round((planHealth.bufferHours % 1) * 60)}m`;

  return (
    <div className="space-y-6">
      {/* Date Header with Controls */}
      <PageHeader
        title="Today - Detailed Schedule"
        subtitle={`${todayDateStr} • Timetable generated by Deterministic Energy Allocation`}
        actions={
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant="outline"
              leftIcon={<Plus className="w-4 h-4" />}
              onClick={() => setIsTaskModalOpen(true)}
            >
              Add Task
            </Button>
            <Button
              size="sm"
              variant="primary"
              leftIcon={<Plus className="w-4 h-4" />}
              onClick={openUrgentModal}
            >
              Add Urgent Task
            </Button>
          </div>
        }
      />

      {/* Plan Health & Metrics Bar */}
      <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
        <MetricCard
          title="Available Time"
          value={availableHoursFormatted}
          subtitle="Total configured focus window"
        />
        <MetricCard
          title="Planned Time"
          value={plannedHoursFormatted}
          subtitle={`${schedule.length} allocated session(s)`}
        />
        <MetricCard
          title="Buffer Time"
          value={bufferHoursFormatted}
          subtitle="Safety cushion for flexibility"
        />
      </div>

      {/* Detailed Schedule Timeline List */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle>Schedule Timeline</CardTitle>
            <p className="text-xs text-slate-500 mt-0.5">
              Click 'Start' to track focus session or check the circle when completed.
            </p>
          </div>
          <Button size="sm" variant="secondary" onClick={() => setIsTaskModalOpen(true)}>
            + Add Focus Slot
          </Button>
        </CardHeader>

        <CardBody className="space-y-3">
          {schedule.length === 0 ? (
            <div className="py-12 text-center space-y-3">
              <div className="w-12 h-12 rounded-full bg-slate-100 flex items-center justify-center mx-auto text-slate-400">
                <CalendarCheck className="w-6 h-6" />
              </div>
              <h4 className="text-sm font-bold text-slate-800">No sessions scheduled for today</h4>
              <p className="text-xs text-slate-500 max-w-sm mx-auto">
                Create a study session or assignment focus slot to activate your daily timeline.
              </p>
              <Button size="sm" variant="primary" onClick={() => setIsTaskModalOpen(true)}>
                + Schedule First Session
              </Button>
            </div>
          ) : (
            schedule.map(slot => (
              <TimelineItem
                key={slot.id}
                slot={slot}
                onComplete={(id, elapsedMinutes) => completeTask(id, elapsedMinutes)}
                onStart={(id) => startTask(id)}
                onPause={(id, elapsedMinutes) => pauseTask(id, Math.max(elapsedMinutes, 1))}
                onDelete={(id) => removeTask(id)}
              />
            ))
          )}
        </CardBody>
      </Card>

      <TaskModal
        isOpen={isTaskModalOpen}
        onClose={() => setIsTaskModalOpen(false)}
        onSuccess={refreshPlan}
      />
    </div>
  );
};
